### ISSUE TITLE
Error when trying to use stubbed impl on Windows

### ISSUE THREAD

**Issue by leonjones1974** [zio/zio-ftp#108]
Unfortunately I need my build to run on Windows as well as linux.
When using the ```ls``` operation on the stub it blows up with:

``` UnsupportedOperationException ```
due to trying to read POSIX attributes.

**Comment by regis-leray** [comment]
Stub implementation is using zio-nio which relying on `java.nio.file.JFiles.list()`
Can you please verify permissions on the specific folder you are providing to the `Ftp.stub()` or show me the code ?

**Comment by leonjones1974** [comment]
Thanks for getting back to me. That's actually really hard because it's code that I can't get off my work machine (without being fired!), and I don't have a personal windows env to reproduce it on.

There's nothing special about the directory. It exists and there's no issue with permissions.
The line of code that causes it to barf is:
```
 _ <- ftp.get.ls("/some_path").runCollect
```
```WindowsFileSystemProvider.readAttributes : 192 ``` is the most useful part of the stack trace.
further down in the stack trace it appears to be making a call to
```Files.getPosixFilePermissions : 2004```

It looks like WindowsFileSystemProvider blows up if it's given a type of anything other than ```BasicFileAttributes```
Here I believe it is being given Posix attributes.

I'm sorry for the less than perfect description but I'm literally hopping between machines and trying to hand-type the relevant info.

Let me know if you need anything else. I can work around it with a mock, but it would be better to get the stub working if we can

**Comment by regis-leray** [comment]
Can you try by using simple `java.nio.file.JFiles.list()` and see if it works ?.
It would be great to have the stacktrace

**Comment by regis-leray** [comment]
You could even try to checkout the code zio-ftp and run `sbt test`

**Comment by leonjones1974** [comment]
Hi.
GitHub is locked down! I could only get it at home... no windows OS!

Files.list works as expected




Sent from Yahoo Mail for iPhone


On Wednesday, August 19, 2020, 8:09 pm, Regis Leray <notifications@github.com> wrote:




You could even try to checkout the code zio-ftp and run sbt test

**Comment by regis-leray** [comment]
Thanks your stacktrace help i found the problem. i will provide a simple fix

**Comment by regis-leray** [comment]
@leonjones1974 what is the version of your windows operating system ?

**Comment by leonjones1974** [comment]
Windows 10 Enterprise (whatever that means!) ;)
Thanks for your help.

**Comment by regis-leray** [comment]
Could you try and provide output
```
val attrs = Files.getPosixFilePermissions(path)
System.out.println(attrs);
```

```
val posixView = Files.getFileAttributeView(path,PosixFileAttributeView.class);
val attrs = posixView.readAttributes();
System.out.println(attrs)
```

**Comment by leonjones1974** [comment]
File.getPosixFilePermissions blows up with the same UnsupportedOperationException I reported initiallyFiles.getFileAttributeView(...) returns null
Sorry I can't get you proper output at this moment, but hope that helps you validate the fix.
Leon
    On Thursday, 20 August 2020, 15:33:50 BST, Regis Leray <notifications@github.com> wrote:  
 
 


Could you try and provide output
val attrs = Files.getPosixFilePermissions(path)
System.out.println(attrs);
val posixView = Files.getFileAttributeView(path,PosixFileAttributeView.class);
val attrs = posixView.readAttributes();
System.out.println(attrs)

**Comment by regis-leray** [comment]
Please try the snapshot release when available, thank you
