### ISSUE TITLE
Add Ftp module with `connect` method and TestFtp

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-ftp#17]
In order to facilitate easier testing of code using ZIO FTP, we should expose `connect` in an optional environment:

```scala
trait Ftp {
  def ftp: Ftp.Service
}
object Ftp {
  trait Service {
    def connect(...): ...
  }
}
```

Then we can make a `TestFtp` that exposes a file system backed by a `Ref[Map[...]]`.

Note: Environment encoding is changing from the above (module pattern) to a slightly different and simpler pattern. So this ticket should probably wait till then (a week or so).

**Comment by regis-leray** [comment]
@jdegoes  i thought Ftp environment would be more something like this 
```scala 
trait Ftp {
  def ftp: Ftp.Service
}
object Ftp {
  trait Service[A] extends FtpClient[A] {
  }
}
```

ZIO environment such as Console, Clock always provide a trait which expose all the functionality. Which give you the ability to access it by using `access/accessM`.

In the current proposal i dont exactly understand how it is supposed to work ?

```scala
def save(path): ZIO[Ftp, IOException, Unit] = ZIO.accessM[Ftp]{ ftp =>
   ftp.connect() // ???
}

**Comment by regis-leray** [comment]
What i was referring is more about performance wise, since we will end up by opening each time a new connection. But i would say i assume it is ok, since we just need to introduce a Connection Pool.

Maybe another zio-pool project :)
