### ISSUE TITLE
UnsecureFtp doesn't download properly

### ISSUE THREAD

**Issue by codingismy11to7** [zio/zio-ftp#213]
While trying to figure out why my downloads weren't working, i traced through the code until I found the call to `FTPClient.retrieveFileStream`, and saw that the javadocs say

```
To finalize the file transfer you must call
     {@link #completePendingCommand  completePendingCommand } and
     check its return value to verify success.
```

I'm not sure of the best way to fix this, as I'm not a ZIO expert, perhaps there's a way to add a cleanup to a stream that only runs if the stream started? Or some way to do it with ZManaged?

In my code I did something like this

```scala
  private def closeXfer[E, A](ftp: FtpAccessors[Client])(res: Either[E, A]) =
    ftp.execute(_.completePendingCommand()).flatMap {
      case false if res.isRight => ZIO.fail(new IOException("File transfer failed"))
      case _                    => ZIO.unit
    }

...

  ftp.readFile(path).run(sink).tapEither(closeXfer(ftp))
```

which consumes the stream and fails the ZIO if it had succeeded but completePendingCommand returns false

**Comment by codingismy11to7** [comment]
again not a ZIO expert but also maybe `ZStream.ensuring` could help?

**Comment by regis-leray** [comment]
@codingismy11to7 i used a ZManaged to be able to execute a release function, but in ZIO world it cannot fail.
So for now i dont how to handle this properly in the close resource

```scala
 ftp.execute(_.completePendingCommand()).flatMap {
      case false => ZIO.fail(new IOException("File transfer failed"))
      case _       => ZIO.unit
    }
```

**Comment by regis-leray** [comment]
@codingismy11to7 i was able to achieve the correct implementation by using ZManaged and throwing Exception by using `orDie`
