### ISSUE TITLE
Ability to disable remote

### ISSUE THREAD

**Issue by gipeshka** [zio/zio-ftp#391]
Hey all!

While using the zio-ftp I've recently faced an issue, when connection to a remote FTP failed with the FTP client error `Host attempting data connection 1.2.3.4 is not same as server 5.6.7.8`. I assume it is related to the fact that the remote FTP is actually load balanced, as [the stackoverflow post](https://stackoverflow.com/questions/57164983/how-to-handle-host-attempting-data-connection-x-x-x-x-is-not-the-same-as-server) describes.

Would it be a good idea to enable a config to disable remote verification on FTP client via `setRemoteVerificationEnabled` when creating it?

Best,
Ilia

**Comment by regis-leray** [comment]
Hello, 
We can add this ftp settings :) 

Im going to see how we can expose the FTPClient, to support any configuration

**Comment by gipeshka** [comment]
thank you
