### ISSUE TITLE
UnsecureFtp: improve readFile Stream finalization 

### ISSUE THREAD

**Issue by regis-leray** [zio/zio-ftp#420]
Hi there,

I recently noticed a problem with zio-ftp. I was trying to read a zip file from the server using [java.util.zip.ZipInputStream](https://docs.oracle.com/en%2Fjava%2Fjavase%2F22%2Fdocs%2Fapi%2F%2F/java.base/java/util/zip/ZipInputStream.html).
So I was just iterating over the entries in the zip file, reading the data from the entries that I'm interested in and it all worked beautifully… until I tried to read another file from the FTP server, which resulted in a file not found error, even though I knew the file was there.
It turns out that iterating over a zip archive with ZipInputStream never results in an attempt to read beyond the end of the file. But due to [the way that finalization of the stream is implemented](https://github.com/zio/zio-ftp/blob/91350dd0a525e6d0583974698bf5dd7c919777d2/zio-ftp/src/main/scala/zio/ftp/UnsecureFtp.scala#L46) (using the ++ operator on a stream), this means that completePendingCommand isn't called, resulting in the problem I've seen.
This might also be the reason for bug https://github.com/zio/zio-ftp/issues/227.

The solution is to use .ensuring for the finalizer. This has the added benefit that it's now possible to read only part of the file and stop processing once you've found the bit you're interested in.
But it leads to another problem: finalizers aren't allowed to throw errors, but completePendingCommand can fail. I could die in that situation, but that doesn't seem right, because die indicates a defect in the program, and when the FTP server decides to be weird, that's not the program's fault. Therefore, I decided to not throw the error from the finalizer but instead delay the error until the next execute call.
I've also improved the error handling so that it doesn't just assume a "File doesn't exist" error but instead exposes the error message given by the FTP server to make it more transparent what's going on.

**Comment by mberndt123** [comment]
That entire issue description is copied verbatim from _my_ description of #410. Straight-up copying my issue description is honestly Not Cool At All.
