### ISSUE TITLE
Add `rename` command

### ISSUE THREAD

**Issue by guersam** [zio/zio-ftp#57]
## Underlying implementations
 - [sftp](https://javadoc.io/doc/com.hierynomus/sshj/latest/index.html)
 - [ftp](http://commons.apache.org/proper/commons-net/apidocs/org/apache/commons/net/ftp/FTPClient.html#rename(java.lang.String,%20java.lang.String))

I'd like to open a PR if you're interested in.

**Comment by regis-leray** [comment]
yees please do 👍

**Comment by regis-leray** [comment]
also since i expose execute, the missing command from FTPClient can be still used https://zio.github.io/zio-ftp/docs/quickstart/quickstart_index#support-any-commands-

```scala
import zio.ftp._
import zio.ftp.Ftp._
import zio.blocking.Blocking

execute(_.rename(oldPath, newPath)).provideLayer(
  unsecure(settings) ++ Blocking.live
)

```

**Comment by regis-leray** [comment]
@guersam do you still need it ? or want to push a PR for that ?

**Comment by guersam** [comment]
@regis-leray  I still would like it, but now it's not the blocker thanks to your workaround.
